/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import org.junit.jupiter.api.Test;


import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void rollMethodReturnsRollsInArray(){
        Library sut = new Library();
        assertEquals(sut.roll(4).length, 4);
    }

    @Test void containsDuplicatesReturnsTrueIfDuplicates(){
        Library sut = new Library();
        int[] testArr = {0,1,1};
        System.out.println(sut.containsDuplicates(testArr));
        assertTrue(sut.containsDuplicates(testArr));
    }

    @Test void calcAvgOfArrayReturnsAvg(){
        Library sut = new Library();
        int[] testArr = {20, 40, 60, 80, 100};
        assertEquals(sut.calcAvgOfArray(testArr), 60);
    }

    @Test void lowestAvgArrayReturnsArrayWithLowestAvg(){
        Library sut = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] test = sut.lowestAvgArrayImproved(weeklyMonthTemperatures);
        assertEquals(Arrays.toString(test),"[55, 54, 60, 53, 59, 57, 61]");
    }
}
