/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int n){
        int[] newArray = new int[n];
        Random r = new Random();
        for(int i = 0; i < n; i++){
            int diceRoll = r.nextInt(6);
            diceRoll += 1;
            newArray[i] = diceRoll;
        }
        return newArray;
    }

    public boolean containsDuplicates(int[] array){
        for(int i = 0; i <= array.length-2; i++){
            for(int j = i+1; j <= array.length-1; j++){
                if(array[i] == array[j]){
                    return true;
                }
            }
        }
        return false;
    }

    public float calcAvgOfArray(int[] array){
        float sum = 0;
        for(float value : array){
            sum += value;
        }
        float avg = sum / array.length;
        return avg;
    }

    public int[] lowestAvgArrayImproved(int[][] array){
        int[] lowestAvgArray = array[0];
        for(int i = 1; i < array.length; i++){
            if(calcAvgOfArray(lowestAvgArray) > calcAvgOfArray(array[i])){
                lowestAvgArray = array[i];
            }
        }
        return lowestAvgArray;
    }

//    public int[] lowestAvgArray(int[][] array){
//        float avg = 0;
//        int[] minArr = new int[array[0].length];
//        for(int i = 0; i < array.length; i++){
//            int sum = 0;
//            for(int j = 0; j < array[i].length; j++){
//                sum += array[i][j];
//            }
//            float sumAvg = sum / array[i].length;
//            if(i == 0) {
//                avg = sumAvg;
//                minArr = array[i];
//            }
//            else if(i > 0 && sumAvg < avg) {
//                avg = sumAvg;
//                minArr = array[i];
//            }
//        }
//        return minArr;
//    }
}
